/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LexicalRouteImport } from './routes/lexical'
import { Route as DndRouteImport } from './routes/dnd'
import { Route as IndexRouteImport } from './routes/index'

const LexicalRoute = LexicalRouteImport.update({
  id: '/lexical',
  path: '/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const DndRoute = DndRouteImport.update({
  id: '/dnd',
  path: '/dnd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dnd': typeof DndRoute
  '/lexical': typeof LexicalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dnd': typeof DndRoute
  '/lexical': typeof LexicalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dnd': typeof DndRoute
  '/lexical': typeof LexicalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dnd' | '/lexical'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dnd' | '/lexical'
  id: '__root__' | '/' | '/dnd' | '/lexical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DndRoute: typeof DndRoute
  LexicalRoute: typeof LexicalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lexical': {
      id: '/lexical'
      path: '/lexical'
      fullPath: '/lexical'
      preLoaderRoute: typeof LexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnd': {
      id: '/dnd'
      path: '/dnd'
      fullPath: '/dnd'
      preLoaderRoute: typeof DndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DndRoute: DndRoute,
  LexicalRoute: LexicalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
