/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreejsRouteImport } from './routes/threejs'
import { Route as LexicalRouteImport } from './routes/lexical'
import { Route as HooksRouteImport } from './routes/hooks'
import { Route as CropperRouteImport } from './routes/cropper'
import { Route as IndexRouteImport } from './routes/index'

const ThreejsRoute = ThreejsRouteImport.update({
  id: '/threejs',
  path: '/threejs',
  getParentRoute: () => rootRouteImport,
} as any)
const LexicalRoute = LexicalRouteImport.update({
  id: '/lexical',
  path: '/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRoute = HooksRouteImport.update({
  id: '/hooks',
  path: '/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const CropperRoute = CropperRouteImport.update({
  id: '/cropper',
  path: '/cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cropper': typeof CropperRoute
  '/hooks': typeof HooksRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cropper': typeof CropperRoute
  '/hooks': typeof HooksRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cropper': typeof CropperRoute
  '/hooks': typeof HooksRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cropper' | '/hooks' | '/lexical' | '/threejs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cropper' | '/hooks' | '/lexical' | '/threejs'
  id: '__root__' | '/' | '/cropper' | '/hooks' | '/lexical' | '/threejs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropperRoute: typeof CropperRoute
  HooksRoute: typeof HooksRoute
  LexicalRoute: typeof LexicalRoute
  ThreejsRoute: typeof ThreejsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threejs': {
      id: '/threejs'
      path: '/threejs'
      fullPath: '/threejs'
      preLoaderRoute: typeof ThreejsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexical': {
      id: '/lexical'
      path: '/lexical'
      fullPath: '/lexical'
      preLoaderRoute: typeof LexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks': {
      id: '/hooks'
      path: '/hooks'
      fullPath: '/hooks'
      preLoaderRoute: typeof HooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cropper': {
      id: '/cropper'
      path: '/cropper'
      fullPath: '/cropper'
      preLoaderRoute: typeof CropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropperRoute: CropperRoute,
  HooksRoute: HooksRoute,
  LexicalRoute: LexicalRoute,
  ThreejsRoute: ThreejsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
