/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreejsRouteImport } from './routes/threejs'
import { Route as LexicalRouteImport } from './routes/lexical'
import { Route as IndexRouteImport } from './routes/index'

const ThreejsRoute = ThreejsRouteImport.update({
  id: '/threejs',
  path: '/threejs',
  getParentRoute: () => rootRouteImport,
} as any)
const LexicalRoute = LexicalRouteImport.update({
  id: '/lexical',
  path: '/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lexical': typeof LexicalRoute
  '/threejs': typeof ThreejsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lexical' | '/threejs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lexical' | '/threejs'
  id: '__root__' | '/' | '/lexical' | '/threejs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LexicalRoute: typeof LexicalRoute
  ThreejsRoute: typeof ThreejsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threejs': {
      id: '/threejs'
      path: '/threejs'
      fullPath: '/threejs'
      preLoaderRoute: typeof ThreejsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexical': {
      id: '/lexical'
      path: '/lexical'
      fullPath: '/lexical'
      preLoaderRoute: typeof LexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LexicalRoute: LexicalRoute,
  ThreejsRoute: ThreejsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
